-- Shared skills catalog for all services.
-- This script is idempotent and can be re-run safely.

CREATE TABLE IF NOT EXISTS skills (
    id UUID PRIMARY KEY,
    skill_name TEXT NOT NULL,
    normalized_skill TEXT NOT NULL UNIQUE,
    category TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

WITH seed(skill_name, category) AS (
    VALUES
        ('Python', 'programming_language'),
        ('Java', 'programming_language'),
        ('JavaScript', 'programming_language'),
        ('TypeScript', 'programming_language'),
        ('C#', 'programming_language'),
        ('C++', 'programming_language'),
        ('Go', 'programming_language'),
        ('Rust', 'programming_language'),
        ('Kotlin', 'programming_language'),
        ('Swift', 'programming_language'),
        ('PHP', 'programming_language'),
        ('Ruby', 'programming_language'),
        ('Scala', 'programming_language'),
        ('Elixir', 'programming_language'),
        ('Dart', 'programming_language'),
        ('SQL', 'programming_language'),
        ('Bash', 'programming_language'),
        ('PowerShell', 'programming_language'),
        ('R', 'programming_language'),
        ('MATLAB', 'programming_language'),

        ('FastAPI', 'backend_framework'),
        ('Django', 'backend_framework'),
        ('Flask', 'backend_framework'),
        ('Spring Boot', 'backend_framework'),
        ('ASP.NET Core', 'backend_framework'),
        ('Node.js', 'backend_framework'),
        ('Express.js', 'backend_framework'),
        ('NestJS', 'backend_framework'),
        ('Ruby on Rails', 'backend_framework'),
        ('Laravel', 'backend_framework'),
        ('GraphQL', 'backend_framework'),
        ('gRPC', 'backend_framework'),
        ('REST API Design', 'backend_framework'),
        ('Microservices', 'backend_framework'),
        ('Domain-Driven Design', 'backend_framework'),

        ('React', 'frontend_framework'),
        ('Next.js', 'frontend_framework'),
        ('Vue.js', 'frontend_framework'),
        ('Nuxt.js', 'frontend_framework'),
        ('Angular', 'frontend_framework'),
        ('Svelte', 'frontend_framework'),
        ('HTML5', 'frontend_framework'),
        ('CSS3', 'frontend_framework'),
        ('Tailwind CSS', 'frontend_framework'),
        ('Sass', 'frontend_framework'),
        ('Webpack', 'frontend_framework'),
        ('Vite', 'frontend_framework'),
        ('Redux', 'frontend_framework'),
        ('React Query', 'frontend_framework'),
        ('Accessibility', 'frontend_framework'),

        ('React Native', 'mobile'),
        ('Flutter', 'mobile'),
        ('Android', 'mobile'),
        ('iOS', 'mobile'),
        ('Jetpack Compose', 'mobile'),
        ('SwiftUI', 'mobile'),

        ('PostgreSQL', 'database'),
        ('MySQL', 'database'),
        ('MariaDB', 'database'),
        ('SQLite', 'database'),
        ('SQL Server', 'database'),
        ('Oracle Database', 'database'),
        ('MongoDB', 'database'),
        ('Redis', 'database'),
        ('Elasticsearch', 'database'),
        ('DynamoDB', 'database'),
        ('Cassandra', 'database'),
        ('Neo4j', 'database'),
        ('Database Modeling', 'database'),
        ('Query Optimization', 'database'),
        ('Data Warehousing', 'database'),

        ('Pandas', 'data_ai_ml'),
        ('NumPy', 'data_ai_ml'),
        ('Scikit-learn', 'data_ai_ml'),
        ('TensorFlow', 'data_ai_ml'),
        ('PyTorch', 'data_ai_ml'),
        ('XGBoost', 'data_ai_ml'),
        ('Apache Spark', 'data_ai_ml'),
        ('Databricks', 'data_ai_ml'),
        ('Airflow', 'data_ai_ml'),
        ('ETL', 'data_ai_ml'),
        ('Feature Engineering', 'data_ai_ml'),
        ('MLOps', 'data_ai_ml'),
        ('LLM Fine-tuning', 'data_ai_ml'),
        ('Prompt Engineering', 'data_ai_ml'),
        ('Vector Databases', 'data_ai_ml'),

        ('Docker', 'devops_cloud'),
        ('Kubernetes', 'devops_cloud'),
        ('Helm', 'devops_cloud'),
        ('Terraform', 'devops_cloud'),
        ('Ansible', 'devops_cloud'),
        ('GitHub Actions', 'devops_cloud'),
        ('GitLab CI', 'devops_cloud'),
        ('Jenkins', 'devops_cloud'),
        ('CircleCI', 'devops_cloud'),
        ('ArgoCD', 'devops_cloud'),
        ('Prometheus', 'devops_cloud'),
        ('Grafana', 'devops_cloud'),
        ('OpenTelemetry', 'devops_cloud'),
        ('Nginx', 'devops_cloud'),
        ('Linux', 'devops_cloud'),

        ('AWS', 'cloud'),
        ('Azure', 'cloud'),
        ('Google Cloud Platform', 'cloud'),
        ('Amazon EC2', 'cloud'),
        ('Amazon S3', 'cloud'),
        ('Amazon RDS', 'cloud'),
        ('AWS Lambda', 'cloud'),
        ('Amazon ECS', 'cloud'),
        ('Amazon EKS', 'cloud'),
        ('Amazon CloudFront', 'cloud'),
        ('AWS IAM', 'cloud'),
        ('Azure Functions', 'cloud'),
        ('Azure DevOps', 'cloud'),
        ('Google Kubernetes Engine', 'cloud'),
        ('Cloud Run', 'cloud'),

        ('Pytest', 'testing_quality'),
        ('Unit Testing', 'testing_quality'),
        ('Integration Testing', 'testing_quality'),
        ('End-to-End Testing', 'testing_quality'),
        ('Test Automation', 'testing_quality'),
        ('Selenium', 'testing_quality'),
        ('Playwright', 'testing_quality'),
        ('Cypress', 'testing_quality'),
        ('Jest', 'testing_quality'),
        ('Vitest', 'testing_quality'),
        ('Load Testing', 'testing_quality'),
        ('k6', 'testing_quality'),
        ('Performance Testing', 'testing_quality'),
        ('Contract Testing', 'testing_quality'),
        ('Code Review', 'testing_quality'),

        ('OAuth 2.0', 'security'),
        ('OpenID Connect', 'security'),
        ('JWT', 'security'),
        ('SAML', 'security'),
        ('RBAC', 'security'),
        ('OWASP Top 10', 'security'),
        ('Web Security', 'security'),
        ('API Security', 'security'),
        ('Secrets Management', 'security'),
        ('Encryption', 'security'),
        ('Hashing', 'security'),
        ('Penetration Testing', 'security'),
        ('Threat Modeling', 'security'),
        ('Vulnerability Management', 'security'),
        ('Zero Trust', 'security'),

        ('System Design', 'architecture'),
        ('Event-Driven Architecture', 'architecture'),
        ('CQRS', 'architecture'),
        ('Event Sourcing', 'architecture'),
        ('Distributed Systems', 'architecture'),
        ('Scalability', 'architecture'),
        ('High Availability', 'architecture'),
        ('Caching Strategies', 'architecture'),
        ('Message Queues', 'architecture'),
        ('Kafka', 'architecture'),
        ('RabbitMQ', 'architecture'),
        ('Service Mesh', 'architecture'),
        ('Observability', 'architecture'),
        ('Technical Documentation', 'architecture'),
        ('API Gateway', 'architecture'),

        ('Git', 'tooling'),
        ('GitHub', 'tooling'),
        ('GitLab', 'tooling'),
        ('Jira', 'tooling'),
        ('Confluence', 'tooling'),
        ('Figma', 'tooling'),
        ('Postman', 'tooling'),
        ('Insomnia', 'tooling'),
        ('Swagger', 'tooling'),
        ('OpenAPI', 'tooling'),
        ('VS Code', 'tooling'),
        ('IntelliJ IDEA', 'tooling'),
        ('Linux Administration', 'tooling'),
        ('Shell Scripting', 'tooling'),
        ('CLI Tooling', 'tooling'),

        ('Agile', 'product_delivery'),
        ('Scrum', 'product_delivery'),
        ('Kanban', 'product_delivery'),
        ('Technical Leadership', 'product_delivery'),
        ('Stakeholder Management', 'product_delivery'),
        ('Mentoring', 'product_delivery'),
        ('Product Discovery', 'product_delivery'),
        ('Requirements Analysis', 'product_delivery'),
        ('Roadmapping', 'product_delivery'),
        ('Cross-functional Collaboration', 'product_delivery'),
        ('Communication', 'product_delivery'),
        ('Incident Response', 'product_delivery'),
        ('Root Cause Analysis', 'product_delivery'),
        ('Release Management', 'product_delivery'),
        ('Change Management', 'product_delivery')
), normalized_seed AS (
    SELECT
        skill_name,
        category,
        regexp_replace(lower(trim(skill_name)), '\\s+', ' ', 'g') AS normalized_skill
    FROM seed
)
INSERT INTO skills (id, skill_name, normalized_skill, category)
SELECT
    (
        substr(md5(normalized_skill), 1, 8) || '-' ||
        substr(md5(normalized_skill), 9, 4) || '-' ||
        substr(md5(normalized_skill), 13, 4) || '-' ||
        substr(md5(normalized_skill), 17, 4) || '-' ||
        substr(md5(normalized_skill), 21, 12)
    )::uuid AS id,
    skill_name,
    normalized_skill,
    category
FROM normalized_seed
ON CONFLICT (normalized_skill) DO UPDATE
SET
    skill_name = EXCLUDED.skill_name,
    category = EXCLUDED.category,
    updated_at = NOW();

-- Keep the catalog aligned with the seeded list.
DELETE FROM skills
WHERE normalized_skill NOT IN (
    SELECT regexp_replace(lower(trim(skill_name)), '\\s+', ' ', 'g')
    FROM (
        VALUES
            ('Python'), ('Java'), ('JavaScript'), ('TypeScript'), ('C#'), ('C++'), ('Go'), ('Rust'), ('Kotlin'), ('Swift'),
            ('PHP'), ('Ruby'), ('Scala'), ('Elixir'), ('Dart'), ('SQL'), ('Bash'), ('PowerShell'), ('R'), ('MATLAB'),
            ('FastAPI'), ('Django'), ('Flask'), ('Spring Boot'), ('ASP.NET Core'), ('Node.js'), ('Express.js'), ('NestJS'),
            ('Ruby on Rails'), ('Laravel'), ('GraphQL'), ('gRPC'), ('REST API Design'), ('Microservices'), ('Domain-Driven Design'),
            ('React'), ('Next.js'), ('Vue.js'), ('Nuxt.js'), ('Angular'), ('Svelte'), ('HTML5'), ('CSS3'), ('Tailwind CSS'), ('Sass'),
            ('Webpack'), ('Vite'), ('Redux'), ('React Query'), ('Accessibility'), ('React Native'), ('Flutter'), ('Android'), ('iOS'),
            ('Jetpack Compose'), ('SwiftUI'), ('PostgreSQL'), ('MySQL'), ('MariaDB'), ('SQLite'), ('SQL Server'), ('Oracle Database'),
            ('MongoDB'), ('Redis'), ('Elasticsearch'), ('DynamoDB'), ('Cassandra'), ('Neo4j'), ('Database Modeling'),
            ('Query Optimization'), ('Data Warehousing'), ('Pandas'), ('NumPy'), ('Scikit-learn'), ('TensorFlow'), ('PyTorch'),
            ('XGBoost'), ('Apache Spark'), ('Databricks'), ('Airflow'), ('ETL'), ('Feature Engineering'), ('MLOps'),
            ('LLM Fine-tuning'), ('Prompt Engineering'), ('Vector Databases'), ('Docker'), ('Kubernetes'), ('Helm'), ('Terraform'),
            ('Ansible'), ('GitHub Actions'), ('GitLab CI'), ('Jenkins'), ('CircleCI'), ('ArgoCD'), ('Prometheus'), ('Grafana'),
            ('OpenTelemetry'), ('Nginx'), ('Linux'), ('AWS'), ('Azure'), ('Google Cloud Platform'), ('Amazon EC2'), ('Amazon S3'),
            ('Amazon RDS'), ('AWS Lambda'), ('Amazon ECS'), ('Amazon EKS'), ('Amazon CloudFront'), ('AWS IAM'),
            ('Azure Functions'), ('Azure DevOps'), ('Google Kubernetes Engine'), ('Cloud Run'), ('Pytest'), ('Unit Testing'),
            ('Integration Testing'), ('End-to-End Testing'), ('Test Automation'), ('Selenium'), ('Playwright'), ('Cypress'),
            ('Jest'), ('Vitest'), ('Load Testing'), ('k6'), ('Performance Testing'), ('Contract Testing'), ('Code Review'),
            ('OAuth 2.0'), ('OpenID Connect'), ('JWT'), ('SAML'), ('RBAC'), ('OWASP Top 10'), ('Web Security'), ('API Security'),
            ('Secrets Management'), ('Encryption'), ('Hashing'), ('Penetration Testing'), ('Threat Modeling'),
            ('Vulnerability Management'), ('Zero Trust'), ('System Design'), ('Event-Driven Architecture'), ('CQRS'),
            ('Event Sourcing'), ('Distributed Systems'), ('Scalability'), ('High Availability'), ('Caching Strategies'),
            ('Message Queues'), ('Kafka'), ('RabbitMQ'), ('Service Mesh'), ('Observability'), ('Technical Documentation'),
            ('API Gateway'), ('Git'), ('GitHub'), ('GitLab'), ('Jira'), ('Confluence'), ('Figma'), ('Postman'), ('Insomnia'),
            ('Swagger'), ('OpenAPI'), ('VS Code'), ('IntelliJ IDEA'), ('Linux Administration'), ('Shell Scripting'),
            ('CLI Tooling'), ('Agile'), ('Scrum'), ('Kanban'), ('Technical Leadership'), ('Stakeholder Management'),
            ('Mentoring'), ('Product Discovery'), ('Requirements Analysis'), ('Roadmapping'), ('Cross-functional Collaboration'),
            ('Communication'), ('Incident Response'), ('Root Cause Analysis'), ('Release Management'), ('Change Management')
    ) AS keep(skill_name)
);
