services:
  gateway-service:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: gateway-service:local
    environment:
      PROFILE_SERVICE_URL: http://host.docker.internal:8080
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - "8000:8000"
