#!/usr/bin/env bash
set -euo pipefail

APP_NAME="${APP_NAME:-cv-match}"
STAGE="${STAGE:-dev}"
REGION="${AWS_REGION:-us-east-1}"
LOCAL_FRONTEND_BASE_URL="${LOCAL_FRONTEND_BASE_URL:-http://localhost:3000}"
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
FRONTEND_ENV_FILE="${FRONTEND_ENV_FILE:-${ROOT_DIR}/frontend/.env.dev}"

LOCAL_FRONTEND_BASE_URL="${LOCAL_FRONTEND_BASE_URL%/}"

log() {
  echo "[$(date -u +'%Y-%m-%dT%H:%M:%SZ')] [sync-frontend-env] $1"
}

require_command() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "Required command not found: $1" >&2
    exit 1
  fi
}

get_stack_output() {
  local stack_name="$1"
  local output_key="$2"

  aws cloudformation describe-stacks \
    --stack-name "${stack_name}" \
    --region "${REGION}" \
    --query "Stacks[0].Outputs[?OutputKey=='${output_key}'].OutputValue | [0]" \
    --output text
}

require_command aws

gateway_stack="${APP_NAME}-${STAGE}-gateway"
auth_stack="${APP_NAME}-${STAGE}-auth"

gateway_url="$(get_stack_output "${gateway_stack}" "GatewayServiceUrl")"
authorization_endpoint="$(get_stack_output "${auth_stack}" "CognitoAuthorizationEndpoint")"
token_endpoint="$(get_stack_output "${auth_stack}" "CognitoTokenEndpoint")"
logout_endpoint="$(get_stack_output "${auth_stack}" "CognitoLogoutEndpoint")"
client_id="$(get_stack_output "${auth_stack}" "CognitoUserPoolClientId")"

for value_name in gateway_url authorization_endpoint token_endpoint logout_endpoint client_id; do
  if [[ -z "${!value_name}" || "${!value_name}" == "None" ]]; then
    echo "Missing required output '${value_name}'. Ensure stacks ${gateway_stack} and ${auth_stack} are deployed." >&2
    exit 1
  fi
done

mkdir -p "$(dirname "${FRONTEND_ENV_FILE}")"

cat > "${FRONTEND_ENV_FILE}" <<EOF
# Auto-generated by scripts/sync-frontend-env-dev.sh
# Generated at $(date -u +'%Y-%m-%dT%H:%M:%SZ')
# Do not edit manually; regenerate after deploy.

API_GATEWAY_BASE_URL=${gateway_url}
NEXT_PUBLIC_API_GATEWAY_BASE_URL=/api/gateway

AUTH_AUTHORIZATION_ENDPOINT=${authorization_endpoint}
AUTH_TOKEN_ENDPOINT=${token_endpoint}
AUTH_LOGOUT_ENDPOINT=${logout_endpoint}
AUTH_LOGOUT_REDIRECT_PARAM=logout_uri
AUTH_CLIENT_ID=${client_id}
AUTH_REDIRECT_URI=${LOCAL_FRONTEND_BASE_URL}/api/auth/callback
AUTH_LOGOUT_REDIRECT_URI=${LOCAL_FRONTEND_BASE_URL}
AUTH_SCOPES=openid email profile
EOF

log "wrote frontend env file: ${FRONTEND_ENV_FILE}"